### ISSUE TITLE
Undefined reference to 'cv::Mat::  ' related errors

### ISSUE THREAD

**Issue by MjiS** [onuralpszr/GFPGAN-ncnn-vulkan#2]
Hi,
I have tried building and running your repository. When I compile it on Ubuntu I get the following errors which I think are related to my OpenCV version or NCNN.
Can you specify the version you have used or recommend?  
Currently, I'm using the latest OpenCV and NCNN versions.
![1](https://github.com/onuralpszr/GFPGAN-ncnn-vulkan/assets/40850864/03875bdd-e8c8-48c8-94f8-884e9a9ec524)
![2](https://github.com/onuralpszr/GFPGAN-ncnn-vulkan/assets/40850864/54dced19-ab3e-4a71-9a48-cce12898f2da)

**Comment by onuralpszr** [comment]
@MjiS  why don't you use cmake/make build ? I see that you doing manually ?

**Comment by onuralpszr** [comment]
@MjiS  what is your distro ? Because I have CI on repo is basically compile for ubuntu system 

https://github.com/onuralpszr/GFPGAN-ncnn-vulkan/blob/main/.github/workflows/build_devCI.yml. 

You can clearly see how I got Vulkan and install Opencv. I didn't compile opencv and I used what ubuntu offer me in their repo. Also Ubuntu on github uses Ubuntu 22.04. I did not use olders systems since they are EOL.

**Comment by onuralpszr** [comment]
> I am also using Ubuntu 22.04.2 LTS. Thanks for pointing out the workflow. I will try your approach of Windows as you have gently updated the workflow too 😃

We have compiled version for windows but I did not tested fully yet.

**Comment by onuralpszr** [comment]
Do not include opencv twice from 2 different source and please USE "cmake" it will make easier.  just install cmake and 

```
git clone --recursive https://github.com/onuralpszr/GFPGAN-ncnn-vulkan.git
cd GFPGAN-ncnn-vulkan
mkdir build
cmake ..
make -jX
```

If you already install opencv and vulkanSDK , which I can see that you have opencv part done you should be able to install without problem.

**Comment by onuralpszr** [comment]
> g++ -o main gfpgan-ncnn-vulkan-demo.cpp face.cpp gfpgan.cpp realesrgan.cpp -L/home/mji/Documents/ncnn/build/install/lib -lncnn -fopenmp -lvulkan -I/home/mji/opencv-4.0.0/build/lib/include/opencv4 -L/home/mji/opencv-4.0.0/build/lib -lopencv_gapi -lopencv_core -lopencv_highgui -lopencv_ml -lopencv_objdetect -lopencv_photo -lopencv_stitching -lopencv_video -lopencv_calib3d -lopencv_features2d -lopencv_dnn -lopencv_flann -lopencv_videoio -lopencv_imgcodecs -lopencv_imgproc -I/home/mji/Documents/GFPGAN-ncnn-vulkan/src/external/ncnn/src -I/home/mji/Documents/GFPGAN-ncnn-vulkan/src/build/external/ncnn/src -I/home/mji/Documents/GFPGAN-ncnn-vulkan/src/include -I/usr/include/opencv4 -L/usr/lib/x86_64-linux-gnu -lglslang -lSPIRV -lHLSL -lOSDependent -lOGLCompiler

Did you type this yourself ?

**Comment by onuralpszr** [comment]
First please remove that opencv 4.0.0 from path do this commands. I see that you have vulkan so that should be fine. 

```console
sudo apt update
sudo apt install libopencv-dev python3-opencv -y
git clone --recursive https://github.com/onuralpszr/GFPGAN-ncnn-vulkan.git
cd GFPGAN-ncnn-vulkan
mkdir build && cd build
cmake ../src
cmake --build . -j 2
```
